apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildpacks-pipeline
spec:
  params:
    - name: name_app
      type: string
      description: app name
    - name: image_app
      type: string
      description: image URL to push
    - name: git_url
      type: string
      description: git repository to use
    - name: source_subpath
      type: string
      description: the source subpath
  workspaces:
    - name: source-workspace # Directory where application source is located. (REQUIRED)
    - name: cache-workspace # Directory where cache is stored (OPTIONAL)
  tasks:
    - name: fetch-repository # This task fetches a repository from github, using the `git-clone` task you installed
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: url
          value: "$(params.git_url)"
        - name: subdirectory
          value: ""  #This needs to be the root directory, otherwise gitclone will create a subdirectory.
        - name: deleteExisting
          value: "true"
    - name: buildpacks # This task uses the `buildpacks` task to build the application
      taskRef:
        name: buildpacks
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source-workspace
        - name: cache
          workspace: cache-workspace
      params:
        - name: APP_IMAGE
          value: "$(params.image_app)" # From trigger-template.yaml
        - name: SOURCE_SUBPATH
          value: $(params.source_subpath) # This is the path within the samples repo you want to build (OPTIONAL, default: "")
        - name: BUILDER_IMAGE
          value: paketobuildpacks/builder:base # This is the builder we want the task to use (REQUIRED)
    - name: restart-deployment
      runAfter:
        - buildpacks
      taskRef:
        name: kubernetes-actions
      params:
      - name: script
        value: |
          kubectl -n default rollout restart deploy $(params.name_app)
