apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kontainer-sh
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/kontainer-sh/kontainer-sh.git
  ref:
    branch: buildpacks

