apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kontainer-sh/kontainer-sh.git
  ref:
    branch: 15-parametrize-hardcoded-settings
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts
