apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-app
  namespace: default
spec:
  interval: 5m
  releaseName: sample-app
  chart:
    spec:
      chart: test-app
      sourceRef:
        kind: GitRepository
        name: kontainer-sh
        namespace: flux-system
