apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ssl-base
  namespace: flux-system
spec:
  interval: 5m
  path: ./ssl-base
  prune: true
  sourceRef:
    kind: GitRepository
    name: kontainer-sh