apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ssl-kustomization
  namespace: flux-system
spec:
  interval: 5m
  path: ./ssl
  dependsOn:
    - name: ssl-base
  prune: true
  validation: client
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: kontainer-sh
  postBuild:
    substitute:
      cm_email: ${cm_email} #from kontainer-base.yaml