apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-events-base
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: kontainer-sh
  path: ./tekton-events-base
  dependsOn:
  - name: tekton-tasks
  prune: true
