apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-events
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: kontainer-sh 
  path: ./tekton-events
  dependsOn:
  - name: tekton-events-base
  prune: true
  validation: client
  targetNamespace: default
  postBuild:
    substitute:
      url_gitrepo: ${url_gitrepo}
      subpath_source: ${subpath_source}
      wh_secret: ${wh_secret}
      app_image: ${app_image} #from kontainer-base.yaml
      cm_email: ${cm_email} #from kontainer-base.yaml