apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: mycluster-registry:5000/hello-world:1.0 # {"$imagepolicy": "default:my-app-policy"}
          imagePullPolicy: Always
          name: hello-world
