apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prod-issuer
spec:
  dependsOn:
    - name: cert-manager
  targetNamespace: default
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@kontainer.sh
    privateKeySecretRef:
      name: prod-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik