apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prod-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${cm_email} #info@kontainer.sh
    privateKeySecretRef:
      name: prod-issuer-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik