apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: staging-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${cm_email} #From ssl-kustomization.yaml
    privateKeySecretRef:
      name: staging-issuer-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik