apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: trigger-el #trigger-demo-el
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - triggerRef: github-listener
  resources:
    kubernetesResource:
      serviceType: NodePort
      servicePort: 80