apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: trigger-el
spec:
  serviceAccountName: tekton-triggers-sa  #-example
  triggers:
    - triggerRef: github-listener
  resources:
    kubernetesResource:
      serviceType: NodePort
      servicePort: 80