apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: gitRepository
      value: $(body.repository.html_url)
    - name: commits
      value: $(body.commits)
    - name: git_url
      value: ${url_gitrepo} #from tekton-events.yaml
    - name: source_subpath
      value: ${subpath_source} #from tekton-events.yaml
    - name: name_app
      value: ${app_name} #from tekton-events.yaml
    - name: image_app
      value: ${app_image} #from tekton-events.yaml