apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-listener
spec:
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: ci-webhook
            secretKey: secret
        - name: "eventTypes"
          value: ["push"]
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: body.ref == 'refs/heads/main'
  bindings:
    - ref: github-binding
  template:
    ref: trigger-demo-template
    params:
      - name: "git_url"
        value: https://github.com/kontainer-sh/sample-app.git
