apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
    - name: commits
      description: The commits which got pushed
    - name: gitRepository
      description: The git repository that hosts context
    - name: git_url
      description: The git repository url
    - name: source_subpath
      description: The source subpath
    - name: image_app
      description: The app image
    - name: name_app
      description: The name of the app
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: app-pipeline-
      spec:
        serviceAccountName: tekton-kubectl-service-account
        pipelineRef:
          name: buildpacks-app-pipeline #mod
        workspaces:
          - name: source-workspace
            subPath: source
            persistentVolumeClaim:
              claimName: buildpacks-source-pvc
          - name: cache-workspace
            subPath: cache
            persistentVolumeClaim:
              claimName: buildpacks-source-pvc
        params:
          - name: image_app
            value: $(tt.params.image_app) #from trigger-binding.yaml
          - name: git_url
            value: $(tt.params.git_url) #from trigger-binding.yaml
          - name: source_subpath
            value: $(tt.params.source_subpath) #from trigger-binding.yaml
          - name: name_app
            value: $(tt.params.name_app) #from trigger-binding.yaml
