apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-demo-template
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
    - name: commits
      description: The commits which got pushed
    - name: gitRepository
      description: The git repository that hosts context
    - name: git_url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: test-pipeline-
      spec:
        serviceAccountName: tekton-kubectl-service-account
        pipelineRef:
          name: buildpacks-test-pipeline
        workspaces:
          - name: source-workspace
            subPath: source
            persistentVolumeClaim:
              claimName: buildpacks-source-pvc
          - name: cache-workspace
            subPath: cache
            persistentVolumeClaim:
              claimName: buildpacks-source-pvc
        params:
          - name: image
            value: k3d-myregistry.localhost:5000/hello-world:1.0
          - name: git_url
            value: $(tt.params.git_url)
          - name: source_subpath
            value: $(tt.params.source_subpath)
