apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: gitRepository
      value: $(body.repository.html_url)
    - name: commits
      value: $(body.commits)
    - name: git_url
      value: https://git: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@github.com/MissMa19/HelloSpringBoot.git
    - name: source_subpath
      value: ""
