apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: gitRepository
      value: $(body.repository.html_url)
    - name: commits
      value: $(body.commits)
    - name: git_url
      value: "https://git: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@github.com/MissMa19/HelloSpringBoot.git"
    - name: source_subpath
      value: ""
