apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appname }} #from sample-frontend.yaml
  name: {{ .Values.appname }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - image: {{ .Values.appimage }}
          imagePullPolicy: Always
          name: {{ .Values.appname }}
