apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appname }} #From helm-frontend.yaml
  name: {{ .Values.appname }} #From helm-frontend.yaml
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Values.appname }} #From helm-frontend.yaml
  sessionAffinity: None
