apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: {{ .Values.issuer }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.host }} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world #{{ .Values.appname }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.secretName }}
